name = "dapp-sveltekit-boilerplate"
type = "javascript"
compatibility_date = "2024-11-03"
node_compat = true
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".svelte-kit/cloudflare"
#account_id = "your_account_id"

[placement]
mode = "smart"

[build]
command = "npm run build"

# Internal Cloudflare database bindings
#[[d1_databases]]
#binding = "DB"
#database_name = "your_database_name"
#database_id = "your_database_id"
#migrations_dir = "drizzle/migrations"

# External database bindings
#[[hyperdrive]]
#binding = "HYPERDRIVE"
#id = "your_database_id"

#[[kv_namespaces]]
#binding = "KV"
#id = "your_kv_id"

#[[r2_bindings]]
#binding = "R2"
#id = "your_r2_id"

[env.production]
name = "dapp-sveltekit-boilerplate-production"

[env.staging]
name = "dapp-sveltekit-boilerplate-staging"
