name = "dapp-sveltekit-boilerplate"
compatibility_date = "2024-11-28"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".svelte-kit/cloudflare"
#account_id = "your_account_id"

[placement]
mode = "smart"

# Internal Cloudflare database bindings
#[[d1_databases]]
#binding = "DB"
#database_name = "your_database_name"
#database_id = "your_database_id"
#migrations_dir = "drizzle/migrations"

# External database bindings
#[[hyperdrive]]
#binding = "HYPERDRIVE"
#id = "your_database_id"

#[[kv_namespaces]]
#binding = "KV"
#id = "your_kv_id"

#[[r2_bindings]]
#binding = "R2"
#id = "your_r2_id"

[env.production]
name = "dapp-sveltekit-boilerplate-production"

[env.production.vars]
NODE_VERSION = "^22"

[env.preview]
name = "dapp-sveltekit-boilerplate-preview"

[env.preview.vars]
NODE_VERSION = "^22"
