name = "dapp-sveltekit-boilerplate"
type = "javascript"
compatibility_flags = ["nodejs_compat_v2"]
#account_id = "your_account_id"

[placement]
mode = "smart"

[build]
command = "npm run build"

#[[d1_databases]]
#binding = "DB1"
#database_name = "your_database_name"
#database_id = "your_database_id"

#[[kv_namespaces]]
#binding = "KV"
#id = "your_kv_id"

#[[r2_bindings]]
#binding = "R2"
#id = "your_r2_id"

[env.production]
name = "dapp-sveltekit-boilerplate-production"

[env.production.vars]
NODE_VERSION = "^20.9.0"

[env.staging]
name = "dapp-sveltekit-boilerplate-staging"

[env.staging.vars]
NODE_VERSION = "^20.9.0"
